services:
  redis:
    image: redis:8-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - web

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: pitomets
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d pitomets" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  postgres-messenger:
    image: postgres:18-alpine
    container_name: postgres-messenger
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_messenger_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d messenger" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - web

  prometheus:
    image: prom/prometheus:v3.9.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - web

  grafana:
    image: grafana/grafana:12.3.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

    depends_on:
      - prometheus
    networks:
      - web

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - web

  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      minio:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    entrypoint: >
      /bin/sh -c "
        echo '⏳ Ждём готовности MinIO...' && sleep 10 &&
        mc alias set myminio http://minio:9000 minioadmin minioadmin &&
        mc mb myminio/pitomets-images --ignore-existing &&
        mc mb myminio/pitomets-avatars --ignore-existing &&
        mc policy set public myminio/pitomets-images &&
        mc policy set public myminio/pitomets-avatars &&
        echo '✅ Бакеты созданы: pitomets-images, pitomets-avatars'
      "
    networks:
      - web


  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168
    networks:
      - web

  kafka-init:
    image: apache/kafka:4.1.1
    depends_on:
      kafka:
        condition: service_started
    entrypoint: [ "/bin/bash", "-c" ]
    command: |
      "
      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic notification.send --partitions 3 --replication-factor 1
      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic notification.sent --partitions 3 --replication-factor 1
      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic notification.failed --partitions 3 --replication-factor 1
      echo 'Topics ready'
      "
    networks:
      - web
  # for testing
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
        - "1025:1025"  # SMTP server
        - "8025:8025"  # Web UI
    restart: unless-stopped
    networks:
      - web

  node_exporter:
    image: prom/node-exporter:v1.10.1
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - web

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4040:4040"
    networks:
      - web

  redis_exporter:
    image: oliver006/redis_exporter:v1.80.2
    container_name: redis_exporter
    restart: unless-stopped
    command: [ "--redis.addr=redis:6379" ]
    depends_on:
      - redis
    ports:
      - "9121:9121"
    networks:
      - web

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.19.0
    container_name: postgres_exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@postgres:5432/pitomets?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "9187:9187"
    networks:
      - web

  postgres_exporter_messenger:
    image: prometheuscommunity/postgres-exporter:v0.19.0
    container_name: postgres_exporter_messenger
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@postgres-messenger:5432/messenger?sslmode=disable"
    depends_on:
      - postgres-messenger
    ports:
      - "9188:9187"
    networks:
      - web

  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.10.0
    container_name: elasticsearch_exporter
    restart: unless-stopped
    environment:
      - ES_URI=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "9114:9114"
    networks:
      - web

  loki:
    image: grafana/loki:3.6.5
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - web

  vector:
    image: timberio/vector:v0.53.0
    container_name: vector
    depends_on:
      - loki
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

volumes:
  postgres_main_data:
  postgres_messenger_data:
  es_data:
  minio-data:

networks:
  web:
    external: true
