ktor {
    deployment {
        port = 8081
        host = "0.0.0.0"
    }

    application {
        modules = [ com.pitomets.messenger.ApplicationKt.module ]
    }

    server {
        websockets {
            pingInterval = 15s
            timeout = 15s
            maxFrameSize = Long.MAX_VALUE
        }
    }
}

