ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
    }

    application {
        modules = [ com.messenger.ApplicationKt.main ]
    }

    server {
        websockets {
            pingInterval = 10s
        }
    }
}
