spring:
  application:
    name: monolit

  datasource:
    url: jdbc:postgresql://postgres:5432/pitomets
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://elasticsearch:9200}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 10
        batch.size: 16384
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true

    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        isolation.level: read_committed

    listener:
      ack-mode: manual_immediate

logging:
  level:
    com.pitomets.monolit: INFO
    com.pitomets.monolit.config.ElasticConfig: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: "" # todo dev
  access-token-ttl: 1
  refresh-token-ttl: 168

admin:
  login: ${ADMIN_LOGIN:admin@admin.com}
  password: ${ADMIN_PASSWORD:pitomets_admin_1488}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,httptrace
  endpoint:
    prometheus:
      enabled: true

minio:
  url: ${MINIO_URL:http://minio:9000}
  bucket: ${MINIO_BUCKET:pitomets-images}  # ← используем переменную
  access-key: minioadmin
  secret-key: minioadmin

messenger:
  url: http://messenger:8081

# топик кафки
notification:
  kafka:
    topics:
      notification-send: notification.send
      notification-sent: notification.sent
      notification-failed: notification.failed

moderation:
  with-animal: ${MODERATION_WITH_ANIMAL:true}
  kafka:
    topics:
      moderation-requested: moderation.requested
      moderation-processed: moderation.processed
