spring.application.name=monolit

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=user
spring.datasource.password=

spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.pitomets.monolit=DEBUG
logging.level.org.springframework.security=DEBUG
