spring:
  application:
    name: monolit

  datasource:
    url: jdbc:postgresql://localhost:5432/pitomets
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

logging:
  level:
    com.pitomets.monolit: INFO
    org.springframework.security: DEBUG

jwt:
  secret: "" # todo dev
  access-token-ttl: 1
  refresh-token-ttl: 168

elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,httptrace
  endpoint:
    prometheus:
      enabled: true

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: minioadmin
  secret-key: minioadmin
  bucket: my-bucket
